Update now only 1 error
Only 1 error left in the whole script even with the "OnCollisionEnter2D" method commented out, I just misspelled causing other errors when commenting out that method. The only left is "Assets\Scripts\ContactWithGround.cs(34,43): error CS1002: ; expected"